[workspace]
channels = ["conda-forge"]
name = "py312-cuda-tests"
platforms = ["win-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.8"

[pypi-dependencies]
torch = { version = ">=2.10", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu128" }
torchaudio = { version = "*", index = "https://download.pytorch.org/whl/cu128" }

[tasks]

[dependencies]
python = "3.12.*"
